# Generated by Django 4.0.2 on 2022-04-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='time',
            new_name='hour',
        ),
    ]
