# Generated by Django 4.0.2 on 2022-04-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_time_training_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='hour',
        ),
        migrations.AddField(
            model_name='training',
            name='time',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=3),
        ),
    ]
