# Generated by Django 4.0.2 on 2022-04-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_pokeball'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokeballs',
            field=models.ManyToManyField(to='main_app.Pokeball'),
        ),
    ]
